Repository FirelyTeam/firely-net-common, pull requests merged in 2021-12, with the labels that each got.

#168 Five W's support
  src/Hl7.Fhir.Support.Poco/Introspection/FhirElementAttribute.cs
  src/Hl7.Fhir.Support.Poco/Introspection/PropertyMapping.cs
Labels: enhancement

#141 Adding IReadOnlyDictionary support
  src/Hl7.Fhir.ElementModel/Types/DateTime.cs
  src/Hl7.Fhir.Support.Poco/Introspection/FhirElementAttribute.cs
  src/Hl7.Fhir.Support.Poco/Model/Base.cs
  src/Hl7.Fhir.Support.Poco/Model/Element.cs
  src/Hl7.Fhir.Support.Poco/Model/Extension.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/BackboneElement.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/BackboneType.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/CodeableConcept.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Coding.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/ContactDetail.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/ContactPoint.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/DomainResource.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Identifier.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Meta.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/OperationOutcome.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Parameters.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Period.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Quantity.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Range.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/Resource.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/ResourceReference.cs
  src/Hl7.Fhir.Support.Poco/Model/Generated/UsageContext.cs
  src/Hl7.Fhir.Support.Poco/Model/Narrative.cs
  src/Hl7.Fhir.Support.Poco/Model/PrimitiveType.cs
  src/Hl7.Fhir.Support.Poco/Validation/AllowedTypesAttribute.cs
  src/Hl7.Fhir.Support.Tests/Serialization/TestDictionaryImplementation.cs
  src/Hl7.Fhir.Support/Utility/FhirReleaseParser.cs
Labels: 4.0.0

#144 Add IReadOnlyDictionary based Json serializer
  src/Hl7.Fhir.Support.Poco.Tests/Hl7.Fhir.Support.Poco.Tests.csproj
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestAddress.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestAttachment.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestBinary.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestBundle.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestCodeSystem.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestEnums.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestHumanName.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestOrganization.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestPatient.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestQuestionnaire.cs
  src/Hl7.Fhir.Support.Poco.Tests/Model/TestSignature.cs
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/JsonFhirSerializationTests.cs
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/SummaryFilterIntegrationTests.cs
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/SummaryFilterTests.cs
  src/Hl7.Fhir.Support.Poco.Tests/Properties/AssemblyInfo.cs
  src/Hl7.Fhir.Support.Poco.Tests/TestData/fp-test-patient.json
  src/Hl7.Fhir.Support.Poco.Tests/TestData/json-edge-cases.json
  src/Hl7.Fhir.Support.Poco.Tests/TestData/mask-text.xml
  src/Hl7.Fhir.Support.Poco/Hl7.Fhir.Support.Poco.csproj
  src/Hl7.Fhir.Support.Poco/Introspection/ClassMapping.cs
  src/Hl7.Fhir.Support.Poco/Model/PrimitiveType.cs
  src/Hl7.Fhir.Support.Poco/Serialization/BundleFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/ElementMetadataFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/JsonFhirConverter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/JsonFhirDictionarySerializer.cs
  src/Hl7.Fhir.Support.Poco/Serialization/JsonSerializerOptionsExtensions.cs
  src/Hl7.Fhir.Support.Poco/Serialization/SerializationFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/TopLevelFilter.cs
Labels: 4.0.0

#147 Added an Xml serializer based on IReadOnlyDictionary.
  build/azure-pipelines.yml
  src/Benchmarks/Benchmarks.csproj
  src/Benchmarks/Program.cs
  src/Benchmarks/SerializationBenchmarks.cs
  src/Benchmarks/TestData/fp-test-patient.json
  src/Benchmarks/TestData/fp-test-patient.xml
  src/Hl7.Fhir.ElementModel/Types/Any.cs
  src/Hl7.Fhir.Serialization/Utility/SerializationUtil.cs
  src/Hl7.Fhir.Support.Poco.Tests/Hl7.Fhir.Support.Poco.Tests.csproj
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/JsonFhirSerializationTests.cs
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/XmlFhirSerializationTests.cs
  src/Hl7.Fhir.Support.Poco.Tests/TestData/fp-test-patient.xml
  src/Hl7.Fhir.Support.Poco/Introspection/ClassMapping.cs
  src/Hl7.Fhir.Support.Poco/Model/Extension.cs
  src/Hl7.Fhir.Support.Poco/Model/PrimitiveType.cs
  src/Hl7.Fhir.Support.Poco/Serialization/BundleFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/ElementMetadataFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/SerializationFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/TopLevelFilter.cs
  src/Hl7.Fhir.Support.Poco/Serialization/XmlFhirDictionarySerializer.cs
  src/Hl7.Fhir.Support.Tests/Serialization/TestDictionaryImplementation.cs
Labels: 4.0.0

#162 Cleanup projectfiles and dependencies
  build/build-variables.yml
  build/templates/test-job-template.yml
  src/Benchmarks/Benchmarks.csproj
  src/Hl7.Fhir.ElementModel/Hl7.Fhir.ElementModel.csproj
  src/Hl7.Fhir.Serialization/Hl7.Fhir.Serialization.csproj
  src/Hl7.Fhir.Support.Poco.Tests/Hl7.Fhir.Support.Poco.Tests.csproj
  src/Hl7.Fhir.Support.Poco/Hl7.Fhir.Support.Poco.csproj
  src/Hl7.Fhir.Support.Tests/Hl7.Fhir.Support.Tests.csproj
  src/Hl7.Fhir.Support.Tests/Serialization/TestDictionaryImplementation.cs
  src/Hl7.Fhir.Support/Hl7.Fhir.Support.csproj
  src/Hl7.FhirPath.Tests/HL7.FhirPath.Tests.csproj
  src/Hl7.FhirPath/Hl7.FhirPath.csproj
  src/firely-net-common-tests.props
  src/firely-net-common.props
  src/firely-net-common.targets
Labels: 4.0.0

#173 Introduce CodedException "everywhere"
  src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirJsonDeserializationTests.cs
  src/Hl7.Fhir.Support.Poco/Introspection/FhirElementAttribute.cs
  src/Hl7.Fhir.Support.Poco/Model/CodeOfT.cs
  src/Hl7.Fhir.Support.Poco/Serialization/DataAnnotationDeserialzationValidator.cs
  src/Hl7.Fhir.Support.Poco/Serialization/DeserializationContext.cs
  src/Hl7.Fhir.Support.Poco/Serialization/DeserializationFailedException.cs
  src/Hl7.Fhir.Support.Poco/Serialization/ExceptionAggregator.cs
  src/Hl7.Fhir.Support.Poco/Serialization/FhirJsonException.cs
  src/Hl7.Fhir.Support.Poco/Serialization/FhirJsonPocoDeserializer.cs
  src/Hl7.Fhir.Support.Poco/Serialization/SystemTextJsonParsingExtensions.cs
  src/Hl7.Fhir.Support.Poco/Validation/AllowedTypesAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/CardinalityAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/CodePatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/CodedValidationException.cs
  src/Hl7.Fhir.Support.Poco/Validation/DatePatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/DateTimePatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/DotNetAttributeValidation.cs
  src/Hl7.Fhir.Support.Poco/Validation/IdPatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/NarrativeXhtmlPatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/OidPatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/TimePatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/UriPatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/UuidPatternAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/ValidateEnumCodeAttribute.cs
  src/Hl7.Fhir.Support.Poco/Validation/ValidationContextExtensions.cs
  src/Hl7.Fhir.Support/Utility/CodedException.cs
  src/Hl7.Fhir.Support/Utility/ICodedException.cs
  src/Hl7.Fhir.Support/Utility/IPositionInfo.cs
Labels: 4.0.0

#174 Fix duplicate evaluation of scalar expressions
  src/Hl7.FhirPath.Tests/Functions/FunctionsTests.cs
  src/Hl7.FhirPath/FhirPath/CompiledExpression.cs
Labels: bug
